[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"

[[mgr.prepend_keymap]]
on = "1"
run = "plugin relative-motions 1"

[[mgr.prepend_keymap]]
on = "2"
run = "plugin relative-motions 2"

[[mgr.prepend_keymap]]
on = "3"
run = "plugin relative-motions 3"

[[mgr.prepend_keymap]]
on = "4"
run = "plugin relative-motions 4"

[[mgr.prepend_keymap]]
on = "5"
run = "plugin relative-motions 5"

[[mgr.prepend_keymap]]
on = "6"
run = "plugin relative-motions 6"

[[mgr.prepend_keymap]]
on = "7"
run = "plugin relative-motions 7"

[[mgr.prepend_keymap]]
on = "8"
run = "plugin relative-motions 8"

[[mgr.prepend_keymap]]
on = "9"
run = "plugin relative-motions 9"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
